### ISSUE TITLE
Adding multiple modals on 1 page

### ISSUE THREAD

**Issue by sjr-admin** [scottaohara/accessible_modal_window#13]
I am working on a site that needs to have multiple modals on 1 page. I started using the code you have here https://codepen.io/scottohara/pen/OEeBJe but it only works with 2 modals. The example here also doesn't seem to work well with multiple modals. Could you help me consolidate the code or point me in the right direction to have multiple ADA-compliant modals on 1 page?

**Comment by scottaohara** [comment]
First of all, that codepen is meant to demonstrate an issue with focusing dialogs on iOS, and is not at all meant to be used in production...

The [demo page contains various modals](https://scottaohara.github.io/accessible_modal_window/tests/general.html), you can check how that's setup vs how you're trying to implement.

Another way to accomplish this would be to review the code proposed for addition in #7 

I'll be doing work in the future on making the script easier to create multiple modals without them all having to exist on document load.  But as I do all of this in my free time, I cannot further assist with how people implement the script in their own projects.  

Thanks
