### ISSUE TITLE
Span in button prevents opening dialog

### ISSUE THREAD

**Issue by 1j01** [scottaohara/accessible_modal_window#24]
Here's a minimal example showing the problem: https://jsfiddle.net/s9v6r2nt/1/  
Clicking in the center of the button doesn't work, only clicking at the very edges (outside the span) can you open the modal.

My real use case is fully styling buttons using a wrapper (`button.functional-button > span.visual-button`), which is the only way I've found to make a nice 3D button push effect without the hit area changing while it's being pressed (that can lead to flickering, or thinking you've pressed the button but you haven't). In this case the entire button didn't work to open the modal because the span took up the entire button. I added `pointer-events: none` to the span as a workaround.
(The app is here, for reference: [midi-recorder.web.app](https://midi-recorder.web.app/). The modal is for recovering recordings, so you'd have to record something  and refresh the page to enable the button, and for that you'd need a MIDI keyboard, or some sort of software MIDI input.)

**Comment by robinpoort** [comment]
@1j01 In case you're still looking for a solution; I ran into the same problem and I'm using the following CSS now to go around the problem:

```css
.functional-button > * {
    pointer-events: none;
}
```

The right solution would be for the plugin to use something like `e.target.closest('[data-modal-open]')` instead of just looking at the button itself.

Anyways, hope this helps :-)

**Comment by scottaohara** [comment]
[not the fix i should have made, but fixed](https://github.com/scottaohara/accessible_modal_window/releases/tag/v3.4.1)
