### ISSUE TITLE
Release new version for CSS fix

### ISSUE THREAD

**Issue by robinpoort** [scottaohara/accessible_modal_window#26]
Hey man, I noticed a missing comma in the CSS file. I wanted to add an issue for that but found out you already fixed that in master. However it's not been released in a release yet. Any chance you're going to release a new version? If so, it might be good to take a look at #24 as well ;-)

Anyways, great plugin nonetheless!

**Comment by scottaohara** [comment]
[released](https://github.com/scottaohara/accessible_modal_window/releases/tag/v3.4.1)  thanks for poking around at this.  hope it was helpful while it was still being maintained.
