### ISSUE TITLE
`input[type="hidden"]` mistakenly marked as focusable

### ISSUE THREAD

**Issue by Kataract** [scottaohara/accessible_modal_window#9]
I'm working with some code that generates hidden inputs with `[type="hidden"]` instead of using the `hidden` attribute.  This case isn't covered in the focusable elements list and if one of the hidden inputs comes before an actual visible input, it gets mistakenly marked as the first thing to focus.

Stripped down markup for a built modal that's broken in this way:
```
<div id="a11y-modal-test-modal" data-modal="" data-modal-close="" role="dialog" class="a11y-modal" tabindex="-1" aria-describedby="md_desc_3331" aria-labelledby="a11y-modal-test-modal_heading">
    <div class="modal-header">
        <h2 class="modal-title a11y-modal__heading" data-modal-description="" id="a11y-modal-test-modal_heading">I'm a heading</h2>
    </div>
    <form method="post" action="#" id="a11y-modal-form-test-modal" role="form" aria-label="a11y modal form test modal">
        <input type="hidden" value="this was hidden" class="js-first-focus"> <- oops
        <div class="modal-body">
            [the rest of the form contents go here, with visible form elements]
        </div>
    </form>
    <div class="modal-footer button-row single-center">
        <button type="button" class="a11y-modal__close-btn is-icon-btn js-last-focus" aria-label="Close"><span data-modal-x=""></span></button>
    </div>
</div>
```

This seems to make tabbing get stuck on the close button, since it's trying to focus a hidden element and that doesn't work.

**Comment by scottaohara** [comment]
Thanks for pointing this out @Kataract!

**Comment by Kataract** [comment]
There's a lot of templates I'd have to update to fix the ordering, since there's a lot of content people can put in there (thanks CMS)  😬

The `role="form"` is just a legacy holdover; there's a script that backports some attributes as a panic defense for older user agents.
